# This is an application meant to deploy my custom-reflector helm chart
# The custom-reflector chart is a custom chart stored in my manifesto repo
# It is meant to take the chart in the repo and apply my custom values to it
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: custom-reflector
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/dom-lc/manifesto.git
      targetRevision: HEAD  # This is the Helm chart version, not HEAD
      path: apps/custom-reflector
      helm:
        valueFiles:
          - $values/apps/custom-reflector/values-sandbox.yaml
    - repoURL: https://github.com/dom-lc/gitops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true